language: python
# This version of python is only used to run tox.
python:
  - 3.5
  - 3.6
script: tox
notifications:
  email: false
install:
  - pip install tox coveralls
after_success:
  - coveralls
